//------------------------------------------------------------------------------
// <auto-generated>
//     Código gerado manualmente para acessar mensagens de erro do recurso .resx.
//     Este arquivo está relacionado ao equipamento e suas mensagens de validação.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Resources;

// Namespace para acesso a recursos localizados (.resx)
namespace Domain
{
    // Atributo indicando que este código foi gerado por ferramenta (aqui usamos "Manual")
    [System.CodeDom.Compiler.GeneratedCode("Manual", "1.0.0")]

    // Informa ao depurador para não entrar neste código automaticamente
    [System.Diagnostics.DebuggerNonUserCode]

    // Indica que esse código é gerado e pode ser tratado de forma especial pelo compilador
    [System.Runtime.CompilerServices.CompilerGenerated]
    public class MensagensDeExceptionEquipamento
    {
        // Gerenciador de recursos (responsável por acessar o arquivo .resx)
        private static ResourceManager resourceMan;

        // Construtor privado para evitar instanciação da classe
        internal MensagensDeExceptionEquipamento() { }

        /// <summary>
        /// Obtém a instância do ResourceManager associada ao arquivo .resx deste recurso.
        /// </summary>
        public static ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    // O nome completo do recurso deve corresponder ao caminho do .resx com namespace
                    resourceMan = new ResourceManager("Domain.Recursos.Equipamento.MensagensDeExceptionEquipamento", typeof(MensagensDeExceptionEquipamento).Assembly);
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Retorna a mensagem: "O nome do equipamento é obrigatório."
        /// </summary>
        public static string NOME_DE_EQUIPAMENTO_OBRIGATORIO
        {
            get
            {
                return ResourceManager.GetString("NOME_DE_EQUIPAMENTO_OBRIGATORIO");
            }
        }

        /// <summary>
        /// Retorna a mensagem: "A descrição do equipamento é obrigatória."
        /// </summary>
        public static string DESCRICAO_DE_EQUIPAMENTO_OBRIGATORIO
        {
            get
            {
                return ResourceManager.GetString("DESCRICAO_DE_EQUIPAMENTO_OBRIGATORIO");
            }
        }
    }
}
