//------------------------------------------------------------------------------
// <auto-generated>
//     Código gerado manualmente para acessar mensagens de erro do recurso .resx.
//     Este arquivo está relacionado ao equipamento e suas mensagens de validação.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    // Namespace para acesso a recursos localizados (.resx)
    using System.Resources;

    // Atributo indicando que este código foi gerado por ferramenta (aqui usamos "Manual")
    [System.CodeDom.Compiler.GeneratedCode("Manual", "1.0.0")]

    // Informa ao depurador para não entrar neste código automaticamente
    [System.Diagnostics.DebuggerNonUserCode]

    // Indica que esse código é gerado e pode ser tratado de forma especial pelo compilador
    [System.Runtime.CompilerServices.CompilerGenerated]
    public class MensagensDeExceptionAutenticacao
    {
        // Gerenciador de recursos (responsável por acessar o arquivo .resx)
        private static ResourceManager resourceMan;

        // Construtor privado para evitar instanciação da classe
        internal MensagensDeExceptionAutenticacao() { }

        /// <summary>
        /// Obtém a instância do ResourceManager associada ao arquivo .resx deste recurso.
        /// </summary>
        public static ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    // O nome completo do recurso deve corresponder ao caminho do .resx com namespace
                    resourceMan = new ResourceManager("Domain.Recursos.Autenticacao.MensagensDeExceptionAutenticacao", typeof(MensagensDeExceptionAutenticacao).Assembly);
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Retorna a mensagem: "Usuário ou senha invalidos."
        /// </summary>
        public static string CREDENCIAIS_INVALIDAS => ResourceManager.GetString("CREDENCIAIS_INVALIDAS");
        
        /// <summary>
        /// Retorna a mensagem: "Voce não tem permição para acessar este recurso."
        /// </summary>
        public static string ACESSO_NEGADO => ResourceManager.GetString("ACESSO_NEGADO");
       
        /// <summary>
        /// Retorna a mensagem: "Token de autenticação inválido."
        /// </summary>
        public static string TOKEN_INVALIDO => ResourceManager.GetString("TOKEN_INVALIDO");
       
        /// <summary>
        /// Retorna a mensagem: "Token de autenticação não enviado."
        /// </summary>
        public static string TOKEN_NAO_FORNECIDO =>ResourceManager.GetString("TOKEN_NAO_FORNECIDO");
       
        /// <summary>
        /// Retorna a mensagem: "Token de autenticação expirado."
        /// </summary>
        public static string TOKEN_EXPIRADO => ResourceManager.GetString("TOKEN_EXPIRADO");
        
    }
}
