//------------------------------------------------------------------------------
// <auto-generated>
//     Código gerado manualmente para acessar mensagens de erro do recurso .resx.
//     Este arquivo está relacionado ao usuário e suas mensagens de validação.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    // Namespace necessário para gerenciar recursos localizados
    using System.Resources;

    // Indica que este código foi gerado manualmente (simulando ferramenta)
    [System.CodeDom.Compiler.GeneratedCode("Manual", "1.0.0")]

    // Ignora esse código no depurador (para facilitar o debug do projeto principal)
    [System.Diagnostics.DebuggerNonUserCode]

    // Indica que essa classe é gerada por ferramenta
    [System.Runtime.CompilerServices.CompilerGenerated]
    public class MensagensDeExceptionUsuario
    {
        // Responsável por acessar os dados do .resx (ResourceManager do .NET)
        private static ResourceManager resourceMan;

        // Construtor privado para evitar instanciamento externo
        internal MensagensDeExceptionUsuario() { }

        /// <summary>
        /// Retorna a instância do ResourceManager para este recurso.
        /// </summary>
        public static ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    // Nome deve ser o caminho completo (namespace + nome do .resx)
                    resourceMan = new ResourceManager("Domain.Recursos.Usuario.MensagensDeExceptionUsuario", typeof(MensagensDeExceptionUsuario).Assembly);
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Retorna a mensagem: "O nome do usuário é obrigatório."
        /// </summary>
        public static string NOME_OBRIGATORIO
        {
            get
            {
                return ResourceManager.GetString("NOME_OBRIGATORIO");
            }
        }

        /// <summary>
        /// Retorna a mensagem: "O e-mail é obrigatório."
        /// </summary>
        public static string EMAIL_OBRIGATORIO
        {
            get
            {
                return ResourceManager.GetString("EMAIL_OBRIGATORIO");
            }
        }

        /// <summary>
        /// Retorna a mensagem: "Este e-mail ja esta sendo usado."
        /// </summary>
        public static string EMAIL_JA_USADO
        {
            get
            {
                return ResourceManager.GetString("EMAIL_JA_USADO");
            }
        }


        /// <summary>
        /// Retorna a mensagem: "A senha é obrigatória."
        /// </summary>
        public static string SENHA_OBRIGATORIO
        {
            get
            {
                return ResourceManager.GetString("SENHA_OBRIGATORIO");
            }
        }

        /// <summary>
        /// Retorna a mensagem: "A senha precisa ter pelo menos 6 caracteres;"
        /// </summary>
        public static string SENHA_INVALIDA
        {
            get
            {
                return ResourceManager.GetString("SENHA_INVALIDA");
            }
        }
    }
}
