//------------------------------------------------------------------------------
// <auto-generated>
//     Código gerado manualmente para acessar mensagens de erro do recurso .resx.
//     Este arquivo está relacionado ao usuário e suas mensagens de validação.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Resources;

// Namespace necessário para gerenciar recursos localizados
namespace Domain
{
    
   

    // Indica que este código foi gerado manualmente (simulando ferramenta)
    [System.CodeDom.Compiler.GeneratedCode("Manual", "1.0.0")]

    // Ignora esse código no depurador (para facilitar o debug do projeto principal)
    [System.Diagnostics.DebuggerNonUserCode]

    // Indica que essa classe é gerada por ferramenta
    [System.Runtime.CompilerServices.CompilerGenerated]
    public class MensagensDeExceptionReservaDeEquipamento
    {
        // Responsável por acessar os dados do .resx (ResourceManager do .NET)
        private static ResourceManager resourceMan;

        // Construtor privado para evitar instanciamento externo
        internal MensagensDeExceptionReservaDeEquipamento() { }

        /// <summary>
        /// Retorna a instância do ResourceManager para este recurso.
        /// </summary>
        public static ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    // Nome deve ser o caminho completo (namespace + nome do .resx)
                    resourceMan = new ResourceManager("Domain.Recursos.ReservaDeEquipamento.MensagensDeExceptionReservaDeEquipamento", typeof(MensagensDeExceptionReservaDeEquipamento).Assembly);
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Retorna a mensagem: "A id do usuário é obrigatória."
        /// </summary>
        public static string ID_USUARIO_OBRIGATORIA => ResourceManager.GetString("ID_USUARIO_OBRIGATORIA"); 

        /// <summary>
        /// Retorna a mensagem: "A id do equipamento é obrigatória."
        /// </summary>
        public static string ID_EQUIPAMENTO_OBRIGATORIA => ResourceManager.GetString("ID_EQUIPAMENTO_OBRIGATORIA");

        /// <summary>
        /// Retorna a mensagem: "O usuário informado é inválido ou não existe."
        /// </summary>
        public static string USUARIO_INVALIDO => ResourceManager.GetString("USUARIO_INVALIDO");     

        /// <summary>
        /// Retorna a mensagem: "O status da reserva é inválido."
        /// </summary>
        public static string STATUS_RESERVA_INVALIDO => ResourceManager.GetString("STATUS_RESERVA_INVALIDO");

        /// <summary>
        /// Retorna a mensagem: "O equipamento já está reservado para essa data."
        /// </summary>
        public static string EQUIPAMENTO_RESERVADO => ResourceManager.GetString("EQUIPAMENTO_RESERVADO");

        /// <summary>
        /// Retorna a mensagem: "O equipamento informado é inválido ou não existe."
        /// </summary>
        public static string EQUIPAMENTO_INVALIDO => ResourceManager.GetString("EQUIPAMENTO_INVALIDO");

         /// <summary>
        /// Retorna a mensagem: "A reserva de equipamento não foi encontrada."
        /// </summary>
        public static string RESERVA_INVALIDA => ResourceManager.GetString("RESERVA_INVALIDA");

        /// <summary>
        /// Retorna a mensagem: "A data da reserva é obrigatória."
        /// </summary>
        public static string DATA_OBRIGATORIA => ResourceManager.GetString("DATA_OBRIGATORIA");

         /// <summary>
        /// Retorna a mensagem: "O status da reserva é obrigatória."
        /// </summary>
        public static string STATUS_RESERVA_OBRIGATORIA => ResourceManager.GetString("STATUS_RESERVA_OBRIGATORIA");
       
    }
}
